name: "geneman-texture-coarse"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "single-image-datamodule"
data:
  image_path: ./load/images/hamburger_rgba.png
  height: 1024
  width: 1024
  default_elevation_deg: 0.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.0
  default_fovy_deg: 20.0
  requires_depth: true
  requires_normal: true
  sampling_type: "default"
  random_camera:
    batch_size: 1
    width: 1024
    height: 1024
    camera_distance_range: [3.0, 3.0]
    fovy_range: [20, 20]
    elevation_range: [-10, 45]
    azimuth_range: [-180, 180]
    eval_height: 1024
    eval_width: 1024
    camera_perturb: 0.
    center_perturb: 0.
    up_perturb: 0.
    eval_camera_distance: 3
    eval_fovy_deg: 20.
    eval_elevation_deg: 0.
    n_val_views: 120
    sampling_type: ${data.sampling_type}

system_type: "geneman-system"
system:
  stage: "texture"
  sampling_type: ${data.sampling_type}
  
  # If using geometry from previous training
  geometry_type: "tetrahedra-sdf-grid"
  geometry_convert_from: ???
  geometry_convert_inherit_texture: false
  geometry:
    radius: 1.0 # consistent with coarse
    isosurface_resolution: 512
    isosurface_deformable_grid: false
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    # n_feature_dims: 8 # albedo3 + roughness1 + metallic1 + bump3
    fix_geometry: true

  # material_type: "pbr-material"
  # material:
  #   material_activation: sigmoid
  #   environment_texture: "load/lights/mud_road_puresky_1k.hdr"
  #   environment_scale: 2.0
  #   min_metallic: 0.0
  #   max_metallic: 0.0
  #   min_roughness: 0.7
  #   max_roughness: 0.9
  #   use_bump: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "solid-color-background"
  background:
    n_output_dims: 3
    color: [1, 1, 1]

  renderer_type: "nvdiff-rasterizer"
  renderer:
    use_sdf_loss: false
    context_type: cuda
    normal_type: 'camera'


  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: ???

  guidance_type: "stable-diffusion-guidance"
  guidance:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    unet_path: "./pretrained_models/geneman-prior2d"
    guidance_scale: 20
    weighting_strategy: sds
    min_step_percent: [0, 0.7, 0.2, 200]
    max_step_percent: [0, 0.85, 0.5, 200]
 
  # prompt_processor_type: "deep-floyd-prompt-processor"
  # prompt_processor:
  #   pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
  #   prompt: ???
  #   use_perp_neg: true

  # guidance_type: "deep-floyd-guidance"
  # guidance:
  #   pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
  #   guidance_scale: 20
  #   min_step_percent: [0, 0.7, 0.2, 200]
  #   max_step_percent: [0, 0.85, 0.5, 200]

  guidance_3d_type: "zero123-guidance"
  guidance_3d:
    pretrained_model_name_or_path:  "./pretrained_models/geneman-prior3d/last.ckpt"
    pretrained_config: "./pretrained_models/geneman-prior3d/prior_3d.yaml"
    cond_image_path: ${data.image_path}
    cond_elevation_deg: ${data.default_elevation_deg}
    cond_azimuth_deg: ${data.default_azimuth_deg}
    cond_camera_distance: ${data.default_camera_distance}
    guidance_scale: 5.0
    min_step_percent: [0, 0.7, 0.2, 200]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.85, 0.5, 200]

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 0.1
    lambda_sds_3d: 0.3
    lambda_rgb: 1000.
    lambda_mask: 0.1

  freq:
    n_ref: 2
    ref_only_steps: 0
    ref_or_guidance: "alternate"  # "accumulate"
    guidance_eval: 0
 
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 2000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 2001